const COMMANDS: &[&str] = &[
    "hotswap_check",
    "hotswap_apply",
    "hotswap_download",
    "hotswap_activate",
    "hotswap_rollback",
    "hotswap_current_version",
    "hotswap_notify_ready",
    "hotswap_configure",
    "hotswap_get_config",
];

fn main() {
    // `cargo publish` verifies a packaged copy under `target/package/...`.
    // The tauri plugin builder writes autogenerated permission files into
    // the source tree, which is forbidden during package verification.
    // Skip regeneration in that context and rely on committed files.
    // Match on the parent directory name rather than the literal string
    // "target/package": the target directory is renameable via
    // CARGO_TARGET_DIR, and a string search misses it when it is.
    if let Ok(manifest_dir) = std::env::var("CARGO_MANIFEST_DIR") {
        let packaging = std::path::Path::new(&manifest_dir)
            .parent()
            .and_then(std::path::Path::file_name)
            .is_some_and(|name| name == "package");
        if packaging {
            return;
        }
    }

    tauri_plugin::Builder::new(COMMANDS).build();
}
